export enum ProjectErrorCode {
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  PROJECT_SLUG_EXISTS = "PROJECT_SLUG_EXISTS",
  PROJECT_CREATE_FAILED = "PROJECT_CREATE_FAILED",
  PROJECT_UPDATE_FAILED = "PROJECT_UPDATE_FAILED",
  PROJECT_DELETE_FAILED = "PROJECT_DELETE_FAILED",
  PROJECT_FETCH_FAILED = "PROJECT_FETCH_FAILED",
  PROJECT_ASSET_INVALID = "PROJECT_ASSET_INVALID",
}
