export enum UserErrorCode {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  LOGIN_FAILED = "LOGIN_FAILED",
  USER_FETCH_FAILED = "USER_FETCH_FAILED",
  USER_UPDATE_FAILED = "USER_UPDATE_FAILED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SESSION_REVOKED = "SESSION_REVOKED",
  LOGOUT_FAILED = "LOGOUT_FAILED",
  PASSWORD_RESET_REQUEST_FAILED = "PASSWORD_RESET_REQUEST_FAILED",
  PROFILE_IMAGE_INVALID = "PROFILE_IMAGE_INVALID",
  PROFILE_IMAGE_NOT_FOUND = "PROFILE_IMAGE_NOT_FOUND",
}
